import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { Toaster } from "@/components/ui/toaster";
import NextTopLoader from 'nextjs-toploader';
import Loader from "./_components/Loader";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: '(prefers-color-scheme: light)',
        url: '/public/logo.svg',
        href: '/public/logo.svg',
      },
      {
        media: '(prefers-color-scheme: dark)',
        url: '/public/logo.svg',
        href:'/public/logo.svg',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       

      <ConvexClientProvider>

      <NextTopLoader  
        color=" #1BFD9C"
        showSpinner={true}
        crawlSpeed={200}
       
        shadow="0 0 10px #2299DD,0 0 5px #2299DD"
       
        showAtBottom={false}
        />
        <Loader />
      {children}
      <Toaster />
        </ConvexClientProvider>  
       
       </body>
    </html>
  );
}
